### ISSUE TITLE
[Conversation] I found you don't need the javascript to blur the background.

### ISSUE THREAD

**Issue by pkkid** [glennraya/vscode-settings-json#20]
Thank you for the video tutorial and examples here.

I found I do not need the vscode-script.js as the following css seems to work great to detect the .quick-input-widget is present and blurs the .monaco-grid-view element when its visible.

```css
.monaco-grid-view {
  transition: filter 0.3s;
}
.monaco-workbench:has(> .quick-input-widget):not(:has(> .quick-input-widget[style*="display: none"])) {
  .monaco-grid-view {
    filter: blur(2px) !important;
  }
}
```
