### ISSUE TITLE
CSS Only blur

### ISSUE THREAD

**Issue by IrishBruse** [glennraya/vscode-settings-json#5]
Loved the video on this and I have been incorperating a bunch of the css you used for my own theme thanks Im using APC instead of css and js loader

here is a fully css driven way of bluring the background when the command pallet is active

```css
.monaco-grid-view:has(~.quick-input-widget:not([style*="display: none;"])) {
  filter: blur(5px)
}
```
